import { SelectOption } from '../types/search';

export const Area: SelectOption[] = [
  {
    label: '대표 지역선택',
    value: '대표 지역선택',
    city: [{ label: '', value: '' }],
  },
  {
    label: '서울특별시',
    value: '서울특별시',
    city: [
      { label: '강남구', value: '강남구' },
      { label: '서초구', value: '서초구' },
      { label: '용산구', value: '용산구' },
      { label: '중구', value: '중구' },
      { label: '종로구', value: '종로구' },
      { label: '성동구', value: '성동구' },
      { label: '광진구', value: '광진구' },
      { label: '동대문구', value: '동대문구' },
      { label: '중랑구', value: '중랑구' },
      { label: '성북구', value: '성북구' },
      { label: '강북구', value: '강북구' },
      { label: '도봉구', value: '도봉구' },
      { label: '노원구', value: '노원구' },
      { label: '은평구', value: '은평구' },
      { label: '서대문구', value: '서대문구' },
      { label: '마포구', value: '마포구' },
      { label: '양천구', value: '양천구' },
      { label: '강서구', value: '강서구' },
      { label: '구로구', value: '구로구' },
      { label: '금천구', value: '금천구' },
      { label: '영등포구', value: '영등포구' },
      { label: '동작구', value: '동작구' },
      { label: '관악구', value: '관악구' },
      { label: '송파구', value: '송파구' },
      { label: '강동구', value: '강동구' },
    ],
  },
  {
    label: '경기도',
    value: '경기도',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '인천광역시',
    value: '인천광역시',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '부산광역시',
    value: '부산광역시',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '광주광역시',
    value: '광주광역시',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '대구광역시',
    value: '대구광역시',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '대전광역시',
    value: '대전광역시',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '울산광역시',
    value: '울산광역시',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '경상남도',
    value: '경상남도',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '경상북도',
    value: '경상북도',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '전라북도',
    value: '전라북도',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '충청북도',
    value: '충청북도',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '충청남도',
    value: '충청남도',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '제주특별자치도',
    value: '제주특별자치도',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '전라남도',
    value: '전라남도',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '세종특별자치시',
    value: '세종특별자치시',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
  {
    label: '강원특별자치도',
    value: '강원특별자치도',
    city: [{ label: 'sd', value: 'sdsd' }],
  },
];
