import React from 'react';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '../styles/globalStyle.scss';
import ReactQueryProviders from '../providers/ReactQueryProvider';
import NavBar from '../common/Nav';
import Footer from '../common/Footer';
import RecoilProviders from '../providers/RecoilProviders';
import { MSWProvider } from '../providers/MSWProvider';

const NotoR = Roboto({
  weight: '400',
  subsets: ['latin'],
});
const NotoB = Roboto({
  weight: '700',
  subsets: ['latin'],
  variable: '--Noto-B',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <RecoilProviders>
      <html lang="kr">
        <body className={`${NotoR.className} ${NotoB.variable}`}>
          <MSWProvider>
            <NavBar />
            <ReactQueryProviders>{children}</ReactQueryProviders>
            <Footer />
            <div id="modal" />
          </MSWProvider>
        </body>
      </html>
    </RecoilProviders>
  );
}
