import React from 'react';

import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import '../styles/globalStyle.scss';

const notosanskr = Noto_Sans_KR({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body className={notosanskr.className}>{children}</body>
    </html>
  );
}
